services:
  app:
    build: .
    container_name: go-throttle
    ports:
      - "8000:8000"
    environment:
      - REDIS_ADDR=redis:6379
    deploy:
      resources:
        limits:
          memory: 64M
    mem_limit: 64m
